
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: slog
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: log message and hours per project
  base: core18
  description: |
    This app logs messages against time spent working on servers
    for different projects. 

  grade: stable
  confinement: strict

  parts:
    slog:
      source: .
      plugin: python
      python-version: python3
#      stage-packages:
#        - click
#        - tinyDB
#        - flask
#        - beautifultable

  apps:
    slog:
      command: bin/slog
