
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: slog
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: log message and hours per project
  description: |
    This app logs messages against time spent working on servers
    for different projects. 

  grade: stable
  confinement: strict # devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: python3

  apps:
    slog:
      command: bin/slog
